# Domain verification for P-U-C Post Fiat validator
# attestation will be added once generated via validator-keys tool

[[VALIDATORS]]
public_key = "nHB6Zc7mhr7swksEgpwTE7Hw7SvZ9cz22T2MECMSXjBeMTeHXQB7"
network = "testnet"
owner_country = "CA"
server_country = "CA"
unl = "https://vl.postfiat.org"

# attestation = "..."   <- add once generated
