[[VALIDATORS]]
public_key = "nHB6Zc7mhr7swksEgpwTE7Hw7SvZ9cz22T2MECMSXjBeMTeHXQB7"
attestation = "FC83AE2D0D0C1E4FD2884DAA600E0643A439B83C8BC80E7AFC5155A0C6F1DD1867BBAB860FECFFDBFBD8C89ABFC2CFD6F07A8707FC1BE888BB21C9086CAB5909"
network = "main"
owner_country = "CA"
server_country = "CA"

[METADATA]
domain = "pft.permanentupperclass.com"
network = "postfiat"
